apiVersion: v1
kind: Service
metadata:
  name: scd-project-frontend-service
spec:
  type: NodePort
  selector:
    app: scd-project-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007

---
apiVersion: v1
kind: Service
metadata:
  name: scd-project-backend-service
spec:
  type: NodePort
  selector:
    app: scd-project-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008